(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> "
p3
sS'layer'
p4
S'/home/juliana/web2py/applications/red_social/controllers/perfil.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n\n@auth.requires_login() \ndef index():\n    id_actual = auth.user.id\n    usuario_actual = db.perfil(db.perfil.user_id == id_actual)\n    form = HTML(\n        H1(usuario_actual.auth_user.first_name + " " \n           + usuario_actual.auth_user.last_name),\n            IMG(_src = URL(\'downloads\',args = usuario_actual.perfil.foto),\n              _width = 160, _height = 280),\n            )\n    return dict(form = form)\n\n\n\ndef downloads():\n     return response.download(request, db)\n\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/juliana/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/juliana/web2py/applications/red_social/controllers/perfil.py", line 20, in <module>\n  File "/home/juliana/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/juliana/web2py/gluon/tools.py", line 3774, in f\n    return action(*a, **b)\n  File "/home/juliana/web2py/applications/red_social/controllers/perfil.py", line 9, in index\n    + usuario_actual.auth_user.last_name),\n  File "/home/juliana/web2py/gluon/packages/dal/pydal/objects.py", line 90, in __getattr__\n    raise AttributeError\nAttributeError\n'
p11
s.